<div class="row">
    <form method="post" action="addArticles.php" class="col-12" enctype="multipart/form-data">
        
        <div class="form-group pl-3">
            <label for="title_art">Titre</label>
            <input class="form-control" id="title_art" type="text" name="title_art" value="<?=$titleArt?>">
        </div>
        <div class="form-group pl-3">
            <label for="content_art">Texte de l'article</label>
            <textarea class="form-control" id="content_art" name="content_art" value="<?=$contentArt?>"></textarea>
        </div>
        <div class="form-group pl-3">
            <label for="file">Nom du fichier:</label>
            <input type="file" name="file" id="file" value="" />
        </div>
        <div class="form-group pl-3">
            <label for="name_categorie">Catégorie</label>
            <select name="name_categorie" id="name_categorie">
            <?php foreach($categories as $categorie): ?>
                <option value="<?=$categorie['id']?>"><?=$categorie['name_categorie']?></option>
               
            <?php endforeach ?>    
            </select>
           
        </div>
              <!-- <div class="form-check form-check-inline pl-3">
            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
            <label class="form-check-label" for="inlineRadio1">Publier</label>
        </div>
        <div class="form-check form-check-inline pl-3">
            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
            <label class="form-check-label" for="inlineRadio2">Brouillon</label>
        </div> -->
        <div class="card-body">
            <button type="submit" class="d-block btn btn-primary">Ajouter</button>
        </div>
    </form>
    
</div>
