<!-- Page Header -->
<header class="masthead" style="background-image: url('uploads/sports.jpeg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Mon Blog</h1>
          <span class="subheading">Mon mien à moi</span>
      </div>
    </div>
  </div>
  </div>
</header>
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      
      <?php foreach($articles as $article): ?>
      <div class="post-preview">
        <a href="articles.php?id=<?=$article['idArt']; ?>">
          <h2 class="post-title">
          <?=$article['title_art'];?>
          </h2>
        </a>
        <p class="post-meta">Posted by
          <a href="#">Start Bootstrap</a>
          <?=$article['create_date'];?></p>
      </div>
      <hr>
      <?php endforeach ?>
      
      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>



